Update pipeline-prometheus.yml

diff --git a/.bluemix/pipeline-prometheus.yml b/.bluemix/pipeline-prometheus.yml
--- a/.bluemix/pipeline-prometheus.yml
+++ b/.bluemix/pipeline-prometheus.yml
@@ -12,19 +12,18 @@ stages:
   - name: Build 
     type: builder
     artifact_dir: ''
-    build_type: gradle
+    build_type: cr
     script: |
-      #!/bin/bash
       #!/bin/bash
       cd monitoring/prometheus
       echo "Creating prometheus file"
-
+      HOST=169.60.26.222
       rm -r prometheus.yml
 
       # Build the yaml file
       YAML_FILE="prometheus.yml"
       echo "Creating config file $YAML_FILE"
-      HOST=http://169.60.26.222
+
       # Build the deployment file
       FILE_CONTENT=$(cat <<EOF''
       global:
@@ -38,7 +37,7 @@ stages:
         scrape_interval: 5s
         metrics_path: '/metrics/'
         static_configs:
-        - targets: ['$HOST:30080']
+        - targets: [$HOST:30080]
         scheme: http
         tls_config:
           insecure_skip_verify: true
@@ -46,7 +45,7 @@ stages:
         scrape_interval: 5s
         metrics_path: '/metrics/'
         static_configs:
-        - targets: ['$HOST:30081']
+        - targets: [$HOST:30081]
         scheme: http
         tls_config:
           insecure_skip_verify: true
@@ -54,7 +53,7 @@ stages:
         scrape_interval: 5s
         metrics_path: '/metrics/'
         static_configs:
-        - targets: ['$HOST:30082']
+        - targets: [$HOST:30082]
         scheme: http
         tls_config:
           insecure_skip_verify: true
@@ -62,79 +61,54 @@ stages:
         scrape_interval: 5s
         metrics_path: '/metrics/'
         static_configs:
-        - targets: ['$HOST:30012']
+        - targets: [$HOST:30012]
         scheme: http
         tls_config:
           insecure_skip_verify: true
+
+
       EOF
       )
 
+
       echo "$FILE_CONTENT" > $YAML_FILE
+
       cat prometheus.yml 
-      cd ../..
-      ./gradlew clean build
-      
-- name: Prepping Containers
-  inputs:
-  - type: job
-    stage: Build
-    job: Build
-  triggers:
-  - type: stage
-  properties:
-  - name: DOCKER_ROOT
-    value: ./monitoring/prometheus
-    type: text
-  - name: DOCKER_FILE
-    value: Dockerfile
-    type: text
-  jobs:
-  - name: Pre-build check
-    type: builder
-    build_type: cr
-    target:
-      region_id: ${REGISTRY_REGION_ID}
-      api_key: ${API_KEY}
-    namespace: ${REGISTRY_NAMESPACE}
-    image_name: liberty-bikes-prometheus
-    script: |
-      #!/bin/bash
+
+
       echo -e "FROM prom/prometheus:v2.4.0\nADD prometheus.yml /etc/prometheus\nEXPOSE 9090" > Dockerfile
 
       cat Dockerfile
 
       echo "REGISTRY_URL=${REGISTRY_URL}"
-            echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
-            echo "IMAGE_NAME=${IMAGE_NAME}"
-            echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
-            echo "DOCKER_ROOT=${DOCKER_ROOT}"
-            echo "DOCKER_FILE=${DOCKER_FILE}"
-            # View build properties
-            if [ -f build.properties ]; then 
-              echo "build.properties:"
-              cat build.properties
-            else 
-              echo "build.properties : not found"
-            fi 
-            # also run 'env' command to find all available env variables
-            # or learn more about the available environment variables at:
-            # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
-            echo "=========================================================="
-            echo "Checking for Dockerfile at the repository root"
-            if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
-            if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
-            if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
-              echo -e "Dockerfile found at: ${DOCKER_FILE}"
-            else
-              echo "Dockerfile not found at: ${DOCKER_FILE}"
-              exit 1
-            fi
-      echo "Linting Dockerfile"
-      
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+      echo "DOCKER_ROOT=${DOCKER_ROOT}"
+      echo "DOCKER_FILE=${DOCKER_FILE}"
+      # View build properties
+      if [ -f build.properties ]; then 
+        echo "build.properties:"
+        cat build.properties
+      else 
+        echo "build.properties : not found"
+      fi 
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+      echo "=========================================================="
+      echo "Checking for Dockerfile at the repository root"
+      if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
+      if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
+      if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
+        echo -e "Dockerfile found at: ${DOCKER_FILE}"
+      else
+        echo "Dockerfile not found at: ${DOCKER_FILE}"
+        exit 1
+      fi
       echo "Linting Dockerfile"
       npm install -g dockerlint
       dockerlint -f ${DOCKER_ROOT}/${DOCKER_FILE}
-
       echo "=========================================================="
       echo "Checking registry current plan and quota"
       bx cr plan
@@ -152,6 +126,24 @@ stages:
       echo -e "Existing images in registry"
       bx cr images --restrict ${REGISTRY_NAMESPACE}
 
+
+      IMAGE_TAG=${TIMESTAMP}
+      if [ ! -z "${GIT_COMMIT}" ]; then
+        GIT_COMMIT_SHORT=$( echo ${GIT_COMMIT} | head -c 8 ) 
+        IMAGE_TAG=${GIT_COMMIT_SHORT}-${IMAGE_TAG}
+      fi
+      if [ ! -z "${GIT_BRANCH}" ]; then IMAGE_TAG=${GIT_BRANCH}-${IMAGE_TAG} ; fi
+      IMAGE_TAG=${BUILD_NUMBER}-${IMAGE_TAG}
+      echo "=========================================================="
+      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${IMAGE_TAG}"
+      if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
+      if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=${DOCKER_ROOT}/Dockerfile ; fi
+      set -x
+      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_ROOT} -f ${DOCKER_FILE}
+      set +x
+      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
+      # Set PIPELINE_IMAGE_URL for subsequent jobs in stage (e.g. Vulnerability Advisor)
+      export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
       echo "=========================================================="
       KEEP=1
       echo -e "PURGING REGISTRY, only keeping last ${KEEP} image(s) based on image digests"
@@ -168,100 +160,12 @@ stages:
       if [[ "$COUNT" -gt 1 ]]; then
         echo "Content of image registry"
         bx cr images
-      fi  
-
-  - name: Build libertybikes-prometheus
-    type: builder
-    build_type: cr
-    target:
-      region_id: ${REGISTRY_REGION_ID}
-      api_key: ${API_KEY}
-    namespace: ${REGISTRY_NAMESPACE}
-    image_name: ${CF_APP_NAME}
-    script: |
-      #!/bin/bash
-
-      # This script does build a Docker image into IBM Cloud Kubernetes Service private image registry, and copies information into
-      # a build.properties file, so they can be reused later on by other scripts (e.g. image url, chart name, ...)
-      echo "REGISTRY_URL=${REGISTRY_URL}"
-      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
-      echo "IMAGE_NAME=${IMAGE_NAME}"
-      echo "BUILD_NUMBER=${BUILD_NUMBER}"
-      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
-      echo "GIT_BRANCH=${GIT_BRANCH}"
-      echo "GIT_COMMIT=${GIT_COMMIT}"
-      echo "DOCKER_ROOT=${DOCKER_ROOT}"
-      echo "DOCKER_FILE=${DOCKER_FILE}"
-
-      # View build properties
-      if [ -f build.properties ]; then 
-        echo "build.properties:"
-        cat build.properties
-      else 
-        echo "build.properties : not found."
       fi 
-
-      # also run 'env' command to find all available env variables
-      # or learn more about the available environment variables at:
-      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
-
-      # To review or change build options use:
-      # bx cr build --help
-
-      echo -e "Existing images in registry"
-      bx cr images
-
-      # Minting image tag using format: BUILD_NUMBER--BRANCH-COMMIT_ID-TIMESTAMP
-      # e.g. 3-master-50da6912-20181123114435
-      # (use build number as first segment to allow image tag as a patch release name according to semantic versioning)
-
-      TIMESTAMP=$( date -u "+%Y%m%d%H%M%S")
-      IMAGE_TAG=${TIMESTAMP}
-      if [ ! -z "${GIT_COMMIT}" ]; then
-        GIT_COMMIT_SHORT=$( echo ${GIT_COMMIT} | head -c 8 ) 
-        IMAGE_TAG=${GIT_COMMIT_SHORT}-${IMAGE_TAG}
-      fi
-      if [ ! -z "${GIT_BRANCH}" ]; then IMAGE_TAG=${GIT_BRANCH}-${IMAGE_TAG} ; fi
-      IMAGE_TAG=${BUILD_NUMBER}-${IMAGE_TAG}
-      echo "=========================================================="
-      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${IMAGE_TAG}"
-      if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
-      if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=${DOCKER_ROOT}/Dockerfile ; fi
-      set -x
-      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_ROOT} -f ${DOCKER_FILE}
-      set +x
-
-      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
-
-      # Set PIPELINE_IMAGE_URL for subsequent jobs in stage (e.g. Vulnerability Advisor)
-      export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
-
-      bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME}
-
-      # Persist env variables into a properties file (build.properties) so that all pipeline stages consuming this
-      # build as input and configured with an environment properties file valued 'build.properties'
-      # will be able to reuse the env variables in their job shell scripts.
-
-      # If already defined build.properties from prior build job, append to it.
-      cp build.properties $ARCHIVE_DIR/ || :
-
-      # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
-      echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
-      echo "IMAGE_TAG=${IMAGE_TAG}" >> $ARCHIVE_DIR/build.properties
-
-      # REGISTRY information from build.properties is used in Helm Chart deployment to generate cluster secret
-      echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
-      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
-      echo "GIT_BRANCH=${GIT_BRANCH}" >> $ARCHIVE_DIR/build.properties
-      echo "File 'build.properties' created for passing env variables to subsequent pipeline jobs:"
-      cat $ARCHIVE_DIR/build.properties
-
-
 - name: Deploy to IBM Cloud
   inputs:
   - type: job
-    stage: Prepping Containers
-    job: Build liberty-bikes-prometheus
+    stage: Build
+    job: Build
   triggers:
   - type: stage
   properties:
@@ -270,10 +174,7 @@ stages:
     type: file
   - name: CLUSTER_NAMESPACE
     value: ${PROD_CLUSTER_NAMESPACE}
-    type: text
-  - name: DEPLOYMENT_FILE
-    value: ./prometheu-deployment.yml
-    type: text      
+    type: text     
   jobs:
   - name: Deploy to Kubernetes
     type: deployer
@@ -284,6 +185,7 @@ stages:
     script: |
       #!/bin/bash
       #set -x
+
       # Use this script as a starting point to create your own deployment.yml
 
       # Make sure the cluster is running and get the ip_address
@@ -300,6 +202,7 @@ stages:
         echo "$IMAGE not set. If using $PIPELINE_IMAGE_URL this variable is only configured when a "Container Registry" build job is used as the stage input."
         exit 1
       fi
+
       echo ""
       echo "Deploy environment variables:"
       echo "NAME=$NAME"
@@ -323,7 +226,7 @@ stages:
         template:
           metadata:
             labels:
-             app: $NAME
+              app: $NAME
           spec:
             containers:
             - name: $NAME
@@ -342,7 +245,7 @@ stages:
         type: NodePort
         ports:
           - port: 9090
-            nodePort: 30084
+            nodePort: 30300
         selector:
           app: $NAME
       EOF
@@ -352,7 +255,6 @@ stages:
       echo "$DEPLOYMENT" > $DEPLOYMENT_FILE
       sed -i 's/$NAME/'"$NAME"'/g' $DEPLOYMENT_FILE
       sed -i 's=$IMAGE='"$IMAGE"'=g' $DEPLOYMENT_FILE
-
 
       # Show the file that is about to be executed
       echo ""
