Update pipeline-prometheus.yml

diff --git a/.bluemix/pipeline-prometheus.yml b/.bluemix/pipeline-prometheus.yml
--- a/.bluemix/pipeline-prometheus.yml
+++ b/.bluemix/pipeline-prometheus.yml
@@ -15,7 +15,65 @@ stages:
     build_type: shell
     script: |
       #!/bin/bash
+      #!/bin/bash
+      cd monitoring/prometheus
+      echo "Creating prometheus file"
+
+      rm -r prometheus.yml
+
+      # Build the yaml file
+      YAML_FILE="prometheus.yml"
+      echo "Creating config file $YAML_FILE"
+
+      # Build the deployment file
+      FILE_CONTENT=$(cat <<EOF''
+      global:
+        scrape_interval:     15s
+
+        external_labels:
+          monitor: 'game-service-monitor'
+
+      scrape_configs:
+      - job_name: 'game-service'
+        scrape_interval: 5s
+        metrics_path: '/metrics/'
+        static_configs:
+        - targets: ['173.193.82.62:32131']
+        scheme: http
+        tls_config:
+          insecure_skip_verify: true
+      - job_name: 'player-service'
+        scrape_interval: 5s
+        metrics_path: '/metrics/'
+        static_configs:
+        - targets: ['173.193.82.62:30554']
+        scheme: http
+        tls_config:
+          insecure_skip_verify: true
+      - job_name: 'auth-service'
+        scrape_interval: 5s
+        metrics_path: '/metrics/'
+        static_configs:
+        - targets: ['173.193.82.62:30082']
+        scheme: http
+        tls_config:
+          insecure_skip_verify: true
+      - job_name: 'frontend'
+        scrape_interval: 5s
+        metrics_path: '/metrics/'
+        static_configs:
+        - targets: ['173.193.82.62:30935']
+        scheme: http
+        tls_config:
+          insecure_skip_verify: true
+      EOF
+      )
+
+      echo "$FILE_CONTENT" > $YAML_FILE
+      cat prometheus.yml 
+      cd ../..
       ./gradlew clean build
+      
 - name: Prepping Containers
   inputs:
   - type: job
@@ -47,29 +105,26 @@ stages:
       echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
       echo "DOCKER_ROOT=${DOCKER_ROOT}"
       echo "DOCKER_FILE=${DOCKER_FILE}"
-
       # View build properties
       if [ -f build.properties ]; then 
-        echo "build.properties:"
-        cat build.properties
+         echo "build.properties:"
+         cat build.properties
       else 
-        echo "build.properties : not found"
+         echo "build.properties : not found"
       fi 
-
-      # also run 'env' command to find all available env variables
-      # or learn more about the available environment variables at:
-      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
-
-      echo "=========================================================="
-      echo "Checking for Dockerfile at the repository root"
-      if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
-      if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
-      if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
-        echo -e "Dockerfile found at: ${DOCKER_FILE}"
-      else
-        echo "Dockerfile not found at: ${DOCKER_FILE}"
-        exit 1
-      fi
+            # also run 'env' command to find all available env variables
+            # or learn more about the available environment variables at:
+            # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+            echo "=========================================================="
+            echo "Checking for Dockerfile at the repository root"
+            if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
+            if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
+            if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
+              echo -e "Dockerfile found at: ${DOCKER_FILE}"
+            else
+              echo "Dockerfile not found at: ${DOCKER_FILE}"
+              exit 1
+            fi
 
       echo "Linting Dockerfile"
       npm install -g dockerlint
@@ -195,6 +250,7 @@ stages:
       echo "GIT_BRANCH=${GIT_BRANCH}" >> $ARCHIVE_DIR/build.properties
       echo "File 'build.properties' created for passing env variables to subsequent pipeline jobs:"
       cat $ARCHIVE_DIR/build.properties
+
 
 - name: Deploy to IBM Cloud
   inputs:
